# Generated by Django 6.0.5 on 2026-06-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepie',
            name='recepie_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
