# Generated by Django 6.0.5 on 2026-06-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_recepie_recepie_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepie',
            name='recepie_link',
            field=models.CharField(blank=True, null=True),
        ),
    ]
